"""add games platforms library_entries tables

Revision ID: 6ef1e56db9e1
Revises: ae0366b8d8e8
Create Date: 2026-06-17 12:12:55.203696

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ef1e56db9e1"
down_revision: str | Sequence[str] | None = "ae0366b8d8e8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pg_trgm powers the fuzzy game-title index below (idx_games_title_trgm);
    # create it here so a fresh database is self-contained (no manual step).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("igdb_id", sa.BigInteger(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("cover_url", sa.String(), nullable=True),
        sa.Column("first_release_date", sa.Date(), nullable=True),
        sa.Column("genres", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("metadata_source", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("igdb_id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "idx_games_title_trgm",
        "games",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.create_table(
        "platforms",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("family", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "library_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "public_id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("game_id", sa.BigInteger(), nullable=False),
        sa.Column("platform_id", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("acquired_at", sa.Date(), nullable=True),
        sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("play_session_next_action", sa.String(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
        ),
        sa.ForeignKeyConstraint(
            ["platform_id"],
            ["platforms.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint(
            "user_id", "game_id", "platform_id", name="uq_library_user_game_platform"
        ),
    )
    op.create_index(
        "idx_library_user_last_played",
        "library_entries",
        ["user_id", sa.literal_column("last_played_at DESC NULLS LAST")],
        unique=False,
    )
    op.create_index(
        "idx_library_user_status", "library_entries", ["user_id", "status"], unique=False
    )
    # ### end Alembic commands ###

    # Seed platforms
    platforms_table = sa.table(
        "platforms",
        sa.column("slug", sa.String),
        sa.column("label", sa.String),
        sa.column("family", sa.String),
    )
    op.bulk_insert(
        platforms_table,
        [
            {"slug": "switch", "label": "Nintendo Switch", "family": "nintendo"},
            {"slug": "ps5", "label": "PlayStation 5", "family": "sony"},
            {"slug": "ps4", "label": "PlayStation 4", "family": "sony"},
            {"slug": "xbox-series", "label": "Xbox Series X|S", "family": "xbox"},
            {"slug": "pc-steam", "label": "PC (Steam)", "family": "pc"},
            {"slug": "pc-gog", "label": "PC (GOG)", "family": "pc"},
            {"slug": "pc-epic", "label": "PC (Epic)", "family": "pc"},
            {"slug": "ios", "label": "iOS", "family": "mobile"},
            {"slug": "android", "label": "Android", "family": "mobile"},
            {"slug": "other", "label": "Other", "family": "other"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_library_user_status", table_name="library_entries")
    op.drop_index("idx_library_user_last_played", table_name="library_entries")
    op.drop_table("library_entries")
    op.drop_table("platforms")
    op.drop_index(
        "idx_games_title_trgm",
        table_name="games",
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    op.drop_table("games")
    # ### end Alembic commands ###
